[package]
name = "supershare"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["rt", "macros", "fs"] }
rand = "0.8"
aes = "0.7"
cfb8 = "0.7"
futures = "0.3"
bytes = "1.1"
lazy_static = "1.4"
log = "0.4"
simple-log = "1.3"
